### ISSUE TITLE
can't move '/etc/nginx/conf.d/service.conf

### ISSUE THREAD

**Issue by prih** [nginx-le/nginx-le#1]
parsons-web_1  | start nginx
parsons-web_1  | ssl_key=le-key.pem, ssl_cert=le-crt.pem
parsons-web_1  | sed: can't move '/etc/nginx/conf.d/service.confaAMhFd' to '/etc/nginx/conf.d/service.conf': Resource busy
parsons-web_1  | sed: can't move '/etc/nginx/conf.d/service.confOAlfDc' to '/etc/nginx/conf.d/service.conf': Resource busy
parsons-web_1  | '/etc/nginx/conf.d' -> '/etc/nginx/conf.d.disabled'
parsons-web_1  | start letsencrypt updater
parsons-web_1  | trying to update letsencrypt ...

rhel 7 | 3.10.0-327.36.1.el7.x86_64
Docker version 1.12.2, build bb80604

**Comment by umputun** [comment]
seems like modern docker doesn't allow mv to mounted files anymore.  Had to change this sed part to work on non-mounted resource. Should be fixed.

**Comment by prih** [comment]
thanks!
but something strange happens when trying to verify the domain, letsencrypt say:

"The server could not connect to the client to verify the domain :: Could not connect to..."

maybe nginx not have time to run... i mean sleep 5;

**Comment by umputun** [comment]
5sec should be enough to start nginx. 

Are you sure your server accessible from outside on 80? I mean firewall, NAT, things like this

**Comment by prih** [comment]
yes, i check this in first thing...
I'm doing build image with sleep 10 for example and try to check problem...

**Comment by umputun** [comment]
and I guess you set LE_FQDN, right? Anyway, if you can post full output of letsencrypt it may help.

**Comment by prih** [comment]
yes np

docker-compose.yml:

  parsons-web:
    restart: always
    image: umputun/nginx-le
    volumes:
    - ./etc/ssl:/etc/nginx/ssl
    - ./etc/nginx-service.conf:/etc/nginx/service.conf
    - ./public_html:/var/www/parsonstemp.boloinc.com/public_html:ro
    environment:
    - TZ=Canada/Central
    - LETSENCRYPT=true
    - LE_EMAIL=prihmail@gmail.com
    - LE_FQDN=parsonstemp.boloinc.com
    ports:
    - 80:80
    - 443:443

>  docker-compose up

Creating network "callbackend_default" with the default driver
Creating callbackend_parsons-web_1
Attaching to callbackend_parsons-web_1
parsons-web_1  | start nginx
parsons-web_1  | ssl_key=le-key.pem, ssl_cert=le-crt.pem
parsons-web_1  | '/etc/nginx/conf.d' -> '/etc/nginx/conf.d.disabled'
parsons-web_1  | start letsencrypt updater
parsons-web_1  | trying to update letsencrypt ...
parsons-web_1  | Failed authorization procedure. parsonstemp.boloinc.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to parsonstemp.boloinc.com
parsons-web_1  | IMPORTANT NOTES:
parsons-web_1  |  - If you lose your account credentials, you can recover through
parsons-web_1  |    e-mails sent to prihmail@gmail.com.
parsons-web_1  |  - The following errors were reported by the server:
parsons-web_1  |
parsons-web_1  |    Domain: parsonstemp.boloinc.com
parsons-web_1  |    Type:   connection
parsons-web_1  |    Detail: Could not connect to parsonstemp.boloinc.com
parsons-web_1  |
parsons-web_1  |    To fix these errors, please make sure that your domain name was
parsons-web_1  |    entered correctly and the DNS A record(s) for that domain
parsons-web_1  |    contain(s) the right IP address. Additionally, please check that
parsons-web_1  |    your computer has a publicly routable IP address and that no
parsons-web_1  |    firewalls are preventing the server from communicating with the
parsons-web_1  |    client. If you're using the webroot plugin, you should also verify
parsons-web_1  |    that you are serving files from the webroot path you provided.
parsons-web_1  |  - Your account credentials have been saved in your Certbot
parsons-web_1  |    configuration directory at /etc/letsencrypt. You should make a
parsons-web_1  |    secure backup of this folder now. This configuration directory will
parsons-web_1  |    also contain certificates and private keys obtained by Certbot so
parsons-web_1  |    making regular backups of this folder is ideal.
parsons-web_1  | cp: can't stat '/etc/letsencrypt/live/parsonstemp.boloinc.com/privkey.pem': No such file or directory
parsons-web_1  | cp: can't stat '/etc/letsencrypt/live/parsonstemp.boloinc.com/fullchain.pem': No such file or directory
parsons-web_1  | '/etc/nginx/conf.d.disabled' -> '/etc/nginx/conf.d'
parsons-web_1  | reload nginx with ssl
parsons-web_1  | 2016/10/19 15:16:33 [emerg] 27#27: BIO_new_file("/etc/nginx/ssl/le-crt.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/le-crt.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
parsons-web_1  | nginx: [emerg] BIO_new_file("/etc/nginx/ssl/le-crt.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/le-crt.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
^CGracefully stopping... (press Ctrl+C again to force)
Killing callbackend_parsons-web_1 ... done

**Comment by prih** [comment]
I think understand what the problem is:

mv -v /etc/nginx/conf.d /etc/nginx/conf.d.disabled

/etc/nginx/conf.d/default.conf point to  /usr/share/nginx/html;
and listen 80 port...

**Comment by umputun** [comment]
yeah, i was able to reproduce it and hopefully got it fixed. Give it a try pls, but it worked for me just fine on fresh DO droplet

**Comment by prih** [comment]
oh... thanks for quick response... i also create pull request with this fixes :)

**Comment by prih** [comment]
sorry for this, but we have problem again:
```
server_name _;
return 301 https://$server_name$request_uri;
```
and we have redirect to https://_

**Comment by prih** [comment]
it is not a problem, but may confuse the user... i mean default nginx config
