### ISSUE TITLE
 --renew-by-default option used intentionally?  

### ISSUE THREAD

**Issue by sergebat** [nginx-le/nginx-le#13]
Current implementation of le.sh uses  --renew-by-default:
https://github.com/umputun/nginx-le/blob/d29a9c765400a922789a9a189a0a75453866a173/script/le.sh#L4

Please correct me if I miss something, but my understanding is that it is called on every container restart.

If this is indeed the case, it may hit letsencrypt rate limits quite easily (5 duplicate certificates per domain per week):
https://letsencrypt.org/docs/rate-limits/

Is it safe to remove this option, or there is a good reason to keep it as is? Thanks!

**Comment by paskal** [comment]
It is indeed being called every container restart. And it is indeed hit the rate pretty easily.
What the alternative you propose? What will happen if this option will be just removed?

**Comment by sergebat** [comment]
Unfortunately, I can't quickly test it right now. 

It _looks_ like   --keep-until-expiring option is what we want here:

> If the requested certificate matches an existing
                        certificate, always keep the existing one until it is
                        due for renewal (for the 'run' subcommand this means
                        reinstall the existing certificate). (default: Ask)

If "due for renewal" means "expiring in less than 30 days", we can make requests for certificate renewal daily, they'll only obtain certificate when necessary. 

Also docs suggest that "--renew" option checks all issued certificates for expiry, and actually renews them if they are expiring in less than 30 days. But I understand it only works if certificate is installed with certbot nginx plugin. 

> As of version 0.10.0, Certbot supports a renew action to check all installed certificates for impending expiry and attempt to renew them. The simplest form is simply

> certbot renew

> This command attempts to renew any previously-obtained certificates that expire in less than 30 days. The same plugin and options that were used at the time the certificate was originally issued will be used for the renewal attempt, unless you specify other plugins or options. Unlike certonly, renew acts on multiple certificates and always takes into account whether each one is near expiry. Because of this, renew is suitable (and designed) for automated use, to allow your system to automatically renew each certificate when appropriate. Since renew only renews certificates that are near expiry it can be run as frequently as you want - since it will usually take no action.

https://certbot.eff.org/docs/using.html#certbot-command-line-options
