### ISSUE TITLE
Question: is it posible to use nginx-le for several third-level domains?

### ISSUE THREAD

**Issue by MrZoidberg** [nginx-le/nginx-le#17]
Hi umputun, got a nub question.

I've tried to add several configurations based on your example conf each having a server_name like XXX.domain.com where XXX is jenkins, teamcity, etc. 

Is this sounds possible?

Thanks!

**Comment by umputun** [comment]
there are two parts here, and both should be possible:

1. issuing a certificate with multiple subdomains - "_for multiple FQDNs you can pass comma-separated list, like LE_FQDN=aaa.example.com,bbb.example.com_"
2. configure multiple sections in your nginx service conf for each subdomain
