### ISSUE TITLE
how set another conf to using miltiple domain?

### ISSUE THREAD

**Issue by ghost** [nginx-le/nginx-le#18]
if set LE_FQDN=first.exam.com,second.exam.com
ssl in second.exam.com using first.exam.com

how set another conf to using miltiple domain?

**Comment by umputun** [comment]
not sure I understand the question. `LE_FQDN=first.exam.com,second.exam.com` means the same (single certificate) issued and used for both domains.

**Comment by ghost** [comment]
done with change or remove old ssl data
thanks
