### ISSUE TITLE
Bump version in docker hub

### ISSUE THREAD

**Issue by paskal** [nginx-le/nginx-le#20]
Hello!

Could you be so kind to rebuild [docker hub](https://hub.docker.com/r/umputun/nginx-le/) image using the latest nginx:alpine-stable? It got TLS 1.3 support in 1.14 but your image seems to be built upon older version.

Thanks!

**Comment by umputun** [comment]
done

**Comment by paskal** [comment]
```
$ docker exec -it 9fbb4236b7a7 nginx -v
nginx version: nginx/1.14.0
```
Thank you!
