### ISSUE TITLE
[Question] PEM_read_bio_X509_AUX("/etc/nginx/ssl/") failed

### ISSUE THREAD

**Issue by DZamataev** [nginx-le/nginx-le#21]
So the last lines in a log are:
```
nginx    | 2018/11/16 15:35:38 [emerg] 22#22: PEM_read_bio_X509_AUX("/etc/nginx/ssl/") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
nginx    | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/ssl/") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
```
Getting these is ok or not?
Probably the files in ssl folder should be named correctly ```.cert``` and ```.key```, not ```.pem```.

**Comment by umputun** [comment]
This is not ok. Most likely somehow it's pointing to corrupted certificate files. Changing extension won't resolve anything. 

Take a look on your etc/ssl/ files, maybe it will give you a clue what went wrong

**Comment by DZamataev** [comment]
Ok it worked after wiping ssl directory. Probably I messed something up when ran it without setting TZ in docker-compose at all.

**Comment by DZamataev** [comment]
Thanks for keeping up a good work, @umputun ! Would you accept some PR with a sample config for using reverse_proxy with port mapping and hostname mapping as for a seconday service-example2.conf?

**Comment by DZamataev** [comment]
Just cuz somebody like me could come up to your great docker container after hitting the inability of the go-to solution https://github.com/jwilder/nginx-proxy to handle multiple ports at multiple hostnames in custom nginx config while still using letsencrypt.

**Comment by umputun** [comment]
sure, I don't mind PR adding missing functionality, bugfixes or documentation/examples. As you may know, multiple hostnames already supported and nothing prevents users from adding different conf files by mapping them directly (via compose) to nginx's `/etc/nginx/conf.d`. You can also have multiple `service*.conf` files and they all should be  handled  just fine https://github.com/umputun/nginx-le/blob/master/script/entrypoint.sh#L22

If you feel documentation is incomplete or/and examples should cover more cases - feel free to PR changes.
