### ISSUE TITLE
Adding new domain won't refresh certificates

### ISSUE THREAD

**Issue by umputun** [nginx-le/nginx-le#23]
Due to #14 refresh can be delayed. Adding a new domain could be very confusing because it won't trigger cert regeneration. 

The workaround is to remove certificates and restart, however, we need a proper automation for this case.

**Comment by paskal** [comment]
I'll try to fix this one. Another issue I've run into is following: dhparams generated on each run, they are not moved to ssl folder so not cached, and other problem they are generated disregarding the fact I don't have dhparams mentions in my configuration.

**Comment by umputun** [comment]
> dhparams generated on each run

Hmm, not sure what you mean https://github.com/umputun/nginx-le/blob/master/script/entrypoint.sh#L31 It generated directly to mounted ssl folder and regen skipped if the file already in.

**Comment by umputun** [comment]
![fmfpg-201811-18144911-7zezj](https://user-images.githubusercontent.com/535880/48677885-2884e600-eb41-11e8-8228-44f4f732bfa6.png)

As you can see it works as expected, i.e. dhparams generated once while ago and it is in `ssl` directory

**Comment by paskal** [comment]
Yes, my bad - too many moving parts when I was cleaning things up. Point about generating it disregarding absence in configuration is true, however I won't change it because it doesn't hurt anybody to have this extra file, but workaround will increase complexity. I'll fix original issue anyway.

**Comment by paskal** [comment]
Command which (with current format of certificate and openssl `1.1.0g-2ubuntu4.1`) shows all domains for multi-domain certificate:
```bash
$ openssl x509 -in ssl/le-crt.pem -text -noout | grep DNS
                DNS:ksinia.net, DNS:terrty.net
```
