### ISSUE TITLE
Predefined ssl ciphers does not works for Android 7

### ISSUE THREAD

**Issue by mik9** [nginx-le/nginx-le#26]
As stated in title: Android 7.0 (and maybe some other versions) clients can't connect to server behind this nginx.

Using ciphers from https://mozilla.github.io/server-side-tls/ssl-config-generator/ with `Intermediate` configuration resolves issue. Ssllabs still score this as A+.

**Comment by umputun** [comment]
done in https://github.com/umputun/nginx-le/commit/d48582e395656f1fd315ab14766587c7a5569a1e

just fyi: user can map any custom nginx.conf via compose volume in case of need
