### ISSUE TITLE
Possibility to add domain/change configuration without long recreation container

### ISSUE THREAD

**Issue by vblz** [nginx-le/nginx-le#28]
Is it possible to change or add a new conf file without recreation of a container? I found only one way to do this: make changes in `service_*.conf` files and then restart the container. But unfortunately this action leds to relative long downtime.
It will be nice to be able to change conf files and FQDN list without downtime of others services (i mean not affected nginx's `server` sections)

**Comment by umputun** [comment]
As far as I recall mapping directory with multiple files as a `volume` (in docker-compose-yml) makes new/changed files available in the container without a restart.

**Comment by vblz** [comment]
As I have gotten from `entrypoint.sh`
https://github.com/umputun/nginx-le/blob/f9dd2c435a02dae020237a5b83c2924e086115b8/script/entrypoint.sh#L22
changing conf file outside the container does not affect the real nginx's conf file, isn't it? Or I misunderstood you and you are talking about exactly this process changes?

And after recall mapping it will be sufficient to just call like `docker exec nginx-le ngins -s reload` to apply new changes or any other mechanism to do it?

**Comment by umputun** [comment]
> changing conf file outside the container does not affect the real nginx's conf file, isn't it? 

yes, correct.

> after recall mapping it will be sufficient to just call like docker exec nginx-le nginx -s reload to apply new changes

if we add a code to watch for conf changes it could also reload nginx. If you can figure a nice and simple way to do it, pls submit a PR.

**Comment by joshkant** [comment]
> Is it possible to change or add a new conf file without recreation of a container? I found only one way to do this: make changes in `service_*.conf` files and then restart the container. But unfortunately this action leds to relative long downtime.
> It will be nice to be able to change conf files and FQDN list without downtime of others services (i mean not affected nginx's `server` sections)

have you tried "docker restart container_name"? it restarts container in few secs and takes changes of service.conf files

**Comment by vblz** [comment]
Yes, of course. The problem is connections drop.
May be it will be useful for someone here: in a case when I need small changes I just go inside container (like `docker exec -it my-nginx-le bash`), edit conf files at `/etc/nginx/conf.d/` and call `nginx -s reload`.
