### ISSUE TITLE
requests LE certificate and will refresh every 10 days ..

### ISSUE THREAD

**Issue by avproton** [nginx-le/nginx-le#32]
Hi

> script/entrypoint.sh requests LE certificate and will refresh every 10 days in case if certificate is close to expiration (30day)

For the test, I launched the server on September 9, the certificate has not yet been updated ... what could be wrong?

**Comment by paskal** [comment]
It checks a certificate expiration date once in [10 days](https://github.com/umputun/nginx-le/blob/master/script/entrypoint.sh#L55), and renews it if [less than 30 days](https://github.com/umputun/nginx-le/blob/master/script/le.sh#L7) left till it's expiration.
What is behavior you expect to see and what you are observing in reality?

**Comment by avproton** [comment]
Ouch ... did not understand the documentation correctly, thanks
