### ISSUE TITLE
gen a wild certificate ? (support dns challenge)

### ISSUE THREAD

**Issue by avproton** [nginx-le/nginx-le#34]
Hi

Is it possible to generate a wild certificate?

**Comment by umputun** [comment]
As far as I recall wildcard certs require dns challenge. nginx-le supports http challenge only.

_I have planned to add support of DNS challenge but never had time to do it. I'll tag the ticket with "help wanted" and maybe someone will make it happen._

**Comment by arsoba** [comment]
@umputun hi!
Could you share your thoughts about DNS challenge? Do you want to use certbot?

**Comment by aponad** [comment]
Hey,
As DNS challenge requires manual DNS update I do not think it is possible to do it completely automatically.
But it can be generated manually.

In your `docker-compose.yml` disable automatic Letsencrypt certificate creation/renewal.
```
    environment:
      - LETSENCRYPT=true
```

```
# after starting nginx-le connect to it
docker exec -it nginx sh

# change `*.example.com` to your domain name
certbot certonly \
    --manual \
    --manual-public-ip-logging-ok \
    --preferred-challenges=dns \
    --email "${LE_EMAIL}" \
    --agree-tos \
    -d "*.example.com"
    
# it will ask you to create/update TXT DNS record
# depending on your DNS provider it can take some time
# you can check if DNS is already updated using dig utility
dig txt _acme-challenge.example.com

# copy certificates for nginx-le to use them
cp -fv /etc/letsencrypt/live/example.com/privkey.pem /etc/nginx/ssl/le-key.pem
cp -fv /etc/letsencrypt/live/example.com/fullchain.pem /etc/nginx/ssl/le-crt.pem
cp -fv /etc/letsencrypt/live/example.com/chain.pem /etc/nginx/ssl/le-chain-crt.pem

# use the same procedure for renewal
```

**Comment by paskal** [comment]
I think it would be nice to write that instruction to documentation, or to Readme.md in that case.
