### ISSUE TITLE
sh: 0: unknown operand

### ISSUE THREAD

**Issue by cr4zyd3v** [nginx-le/nginx-le#36]
Hi! first of all, thanks for this awesome image!
I have been using it for a while and noticed this "unknown operand" warning when running on non daemon mode.. Until now, I have not seen any problems, but I could not figure how to resolve it..
Any thoughts on  this? Thanks in advance.
```
nginx_1     | start nginx
nginx_1     | ssl_key=le-key.pem, ssl_cert=le-crt.pem, ssl_chain_cert=le-chain-crt.pem
nginx_1     | sh: 0: unknown operand
nginx_1     | '/etc/nginx/conf.d' -> '/etc/nginx/conf.d.disabled'
```

**Comment by paskal** [comment]
Thanks for the report! Would you be so kind as to clarify what is a non-daemon mode? Also, is it just an error you see in the log, or the container doesn't start at all?

**Comment by cr4zyd3v** [comment]
Hey, thanks for your response! the container starts and works as expected, but this error shows always I do start the docker image.. Regarding the non daemon mode, it is about the docker-compose up command but without the -d flag.. Also, I use multiple domains on the environment config. Everything works fine, I am just curious about it

**Comment by paskal** [comment]
I'll test it when I'll have time. To clarify, as something non-blocking this is a low priority for me.

I recall what I've fixed some of the problems in this image shell script, but it seems that something is still in place. It would be helpful if you would post your configuration to Pastebin so if it's not reproducible on mine, I would be able to track the difference between mine and yours.

**Comment by umputun** [comment]
@marciks pls make sure you have the latest stable version. I kind of recall the issue (or similar one) back in days and it had smth to do with the legacy base image.

**Comment by paskal** [comment]
Can not reproduce:
```
nginx             | start nginx
nginx             | ssl_key=le-key.pem, ssl_cert=le-crt.pem, ssl_chain_cert=le-chain-crt.pem
nginx             | '/etc/nginx/service1.conf' -> '/etc/nginx/conf.d/service1.conf'
nginx             | '/etc/nginx/service2.conf' -> '/etc/nginx/conf.d/service2.conf'
nginx             | '/etc/nginx/service3.conf' -> '/etc/nginx/conf.d/service3.conf'
nginx             | '/etc/nginx/conf.d' -> '/etc/nginx/conf.d.disabled'
nginx             | start letsencrypt updater
nginx             | trying to update letsencrypt ...
nginx             | letsencrypt certificate /etc/nginx/ssl/le-crt.pem still valid
nginx             | '/etc/nginx/conf.d.disabled' -> '/etc/nginx/conf.d'
nginx             | reload nginx with ssl
nginx             | 2020/02/13 20:50:27 [notice] 34#34: signal process started
```

**Comment by cr4zyd3v** [comment]
Hey guys, I have tested again with latest configs and the warning did not appear .. the only diference I was able to notice was the # in `if [ ${#SERVICES} -ne 0 ]; then` it was missing in my early entrypoint file.. not sure if it was the problem, but now its fixed! thanks again
