### ISSUE TITLE
SSL lab grade is B

### ISSUE THREAD

**Issue by dimkalinux** [nginx-le/nginx-le#38]
Hi,

SSl labs report: This server supports TLS 1.0 and TLS 1.1. Grade capped to B.
See https://blog.qualys.com/ssllabs/2018/11/19/grade-change-for-tls-1-0-and-tls-1-1-protocols

I think maybe it is time to remove TLS 1.0 and TLS 1.1 support fron nginx config?

**Comment by paskal** [comment]
Sounds sane: Chrome removed support for it a [year ago](https://securityboulevard.com/2019/01/google-chrome-drops-support-for-tls-1-0-and-1-1/).
