### ISSUE TITLE
"BEGIN TRUSTED CERTIFICATE" is expected

### ISSUE THREAD

**Issue by sergentum** [nginx-le/nginx-le#42]
Hi, I got this issue:
_nginx: [emerg] cannot load certificate "/etc/nginx/ssl/": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)_

Found the solution here:
https://stackoverflow.com/questions/51899844/nginx-ssl-no-start-line-expecting-trusted-certificate/52085885

put -trustout into params of le.sh but still no luck.

Can anybody check and maybe update scripts?

**Comment by umputun** [comment]
I can't reproduce the issue. Can you share your compose pls and the part of nginx.conf related to ssl

**Comment by sergentum** [comment]
can it be caused by 2 level domain? I'm trying to certify _mydomain_.**mooo.com** provided by freedns.com

**Comment by paskal** [comment]
Impossible to say without your docker-compose.yaml and nginx configuration. I have multiple domains including the second level ones and have no problems with them.

**Comment by sergentum** [comment]
There wasn't much changes. Here I just put domain and email.
`version: '2'
services:

    nginx:
        build: .
        image: umputun/nginx-le:latest
        hostname: nginx
        restart: always
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./etc/ssl:/etc/nginx/ssl
            - ./etc/service-example.conf:/etc/nginx/service.conf
            # - ./etc/service-example-2.conf:/etc/nginx/service2.conf # more services, should be service*.conf
        ports:
            - "80:80"
            - "443:443"

        environment:
            - LETSENCRYPT=true
            - LE_EMAIL=myemail@gmail.com
            - LE_FQDN=mydomain.mooo.com
            #- SSL_CERT=le-crt.pem
            #- SSL_KEY=le-key.pem
            #- SSL_CHAIN_CERT=le-chain-crt.pem
`

`user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;

    keepalive_timeout  65;
    server_tokens off;

    limit_conn_zone $binary_remote_addr zone=perip:10m;
    limit_conn_zone $server_name zone=perserver:10m;

    client_body_buffer_size  4K;
    client_header_buffer_size 4k;
    client_max_body_size 4k;
    large_client_header_buffers 2 4k;


    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/ssl/dhparams.pem;
    ssl_stapling on;
    ssl_session_cache shared:SSL:50m;
    ssl_stapling_verify on;
    ssl_ecdh_curve secp384r1;
    resolver 8.8.8.8;

    gzip on;
    gzip_types text/plain application/json text/css application/javascript application/x-javascript text/javascript text/xml application/xml application/rss+xml application/atom+xml application/rdf+xml;
    gzip_min_length 1000;
    gzip_proxied any;

    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    server {
        listen 80;
        server_name mydomain.mooo.com;

        root   /usr/share/nginx/html;

        location /.well-known/ {}  # do not redirect requests letsencrypt

        location / {  # the default location redirects to https
            proxy_pass  http://10.8.0.3:8123/;
        }
    }

    include /etc/nginx/conf.d/*.conf;
}

stream {
    include /etc/nginx/stream.d/*.conf;
}
`

**Comment by sergentum** [comment]
i'm sorry there are symbols that brake format

**Comment by umputun** [comment]
do you see a good-looking certificate in your `./etc/ssl`?  I suspect some kind of permission issue for this directory

**Comment by sergentum** [comment]
yes, i see files:
le-key.pem
le-crt.pem
le-chain-crt.pem
dhparams.pem
I can't open some of them when docker is up. But when it's down, i can read write them.

**Comment by fedy95** [comment]
Can you show the contents of a ssl-directory? `ls -la ssl/` or something like that

**Comment by umputun** [comment]
> I can't open some of them when docker is up. But when it's down, I can read write them.

This is an important detail. Does it mean you run this container on windows?

**Comment by sergentum** [comment]
no, i'm trying to make it work on aws linux machine

**Comment by sergentum** [comment]
> Can you show the contents of a ssl-directory? `ls -la ssl/` or something like that

isn't it /etc/ssl dir with pem files which i already provided? or you talking about sizes?

**Comment by sergentum** [comment]
[ec2-user@ip ssl]$ ls -la
total 16
drwxr-xr-x 2 root     root       86 Sep 22 18:53 .
drwxrwxr-x 3 ec2-user ec2-user   45 Sep 22 18:35 ..
-rw------- 1 root     root      424 Sep 22 18:52 dhparams.pem
-rw-r--r-- 1 root     root     1647 Sep 22 18:53 le-chain-crt.pem
-rw-r--r-- 1 root     root     3574 Sep 22 18:53 le-crt.pem
-rw------- 1 root     root     1704 Sep 22 18:53 le-key.pem

**Comment by fedy95** [comment]
> isn't it /etc/ssl dir with pem files which i already provided? or you talking about sizes?

I wanted to look directory permissions, looks correct...

**Comment by umputun** [comment]
there is something with your setup we don't see. I'm not sure what is this, but smth is not right. The fact, you "can't open some of them when docker is up" is odd. As you container up and running you should be able to read files, at least on linux.

You can  try to do `docker exec -it nginx cat /etc/nginx/ssl/le-crt.pem` to see if cert is even readable/accessible from your container.

Another direction - do you use the latest version of nginx-le? Try to do `docker pull umputun/nginx-le:latest` or change your compose's image directive to nginx-le:1.3.0

**Comment by sergentum** [comment]
> do you use the latest version of nginx-le

yes, just did docker-compose pull

> docker exec -it nginx cat /etc/nginx/ssl/le-crt.pem

it worked fine.

> there is something with your setup we don't see

I changed almost nothing, only what was needed - domain, email - that's all

**Comment by umputun** [comment]
> it worked fine.

What exactly "worked fine" means? Did you see the certificate printed and the first line is `-----BEGIN CERTIFICATE-----` ?
Also, pls confirm - is this correct and repeatable "I can't open some of them when docker is up. But when it's down, I can read write to them." 

See, we are guessing here and trying to figure out what the possible reason can be. Whatever it is, this is (most likely) something with your local system. Based on the info you provided my best guess is some sort of special docker configuration or some sort of permissions control. This is why I have asked about "can't open some of them when docker is up". Another theory is some kind of encoding issue, but I can't think of any scenario of how it can happen.

**Comment by sergentum** [comment]
> Did you see the certificate printed and the first line is `-----BEGIN CERTIFICATE-----` ?

yes, sure, i meant that.


> is this correct and repeatable "I can't open some of them when docker is up

sorry, that was just matter of sudo. cat le-key.pem and  le-chain-crt.pem  wasn't possible, but it works with sudo.


> something with your local system

doubt that, because it quite fresh aws machine.

In your working servers there're no TRUSTED word in header of crt? Isn't it a config issue?

**Comment by umputun** [comment]
TRUSTED is not supposed to be in. I just installed a fresh instance (on Digital Ocean) and nginx-le got certs just fine, works with nginx as expected. Neither le-crt.pem or le-chain-crt.pem have TRUSTED in the header.

**Comment by umputun** [comment]
is this config file you provided the only one you have? Your proxy_pass to http://10.8.0.3:8123/; implies another part you omitted.

**Comment by paskal** [comment]
To prevent playing ping-ping in this chat, @sergentum can you please post all Nginx configuration in single gist (it can contain multiple files) on  [gist.github.com](https://gist.github.com/)?
Also, do I understand correctly that after the message `nginx: [emerg] cannot load certificate ...` in the log nginx stops and the container fails to start? Can you post the complete log of the container start alongside configuration, please?

**Comment by umputun** [comment]
I was able to reproduce the issue (by accident). As expected it has nothing to do with "TRUSTED CERTIFICATE". Something went wrong with certificates substitution and I see this inside of nginx config:

```
ssl_certificate         /etc/nginx/ssl/;
ssl_certificate_key     /etc/nginx/ssl/;
ssl_trusted_certificate /etc/nginx/ssl/;
```

@paskal - I think this was yours change to support multiple FQDNs? Could you pls take a look? In my case, it happens with `- LE_FQDN=safesecret.info,feedmaster.umputun.com,umputun.com,umputun.feed-master.com` 

@sergentum - a simple workaround is to change your nginx's service with the absolute paths to the certificate, i.e.

```
    ssl_certificate         /etc/nginx/ssl/le-crt.pem;
    ssl_certificate_key     /etc/nginx/ssl/le-key.pem;
    ssl_trusted_certificate /etc/nginx/ssl/le-chain-crt.pem;
```

**Comment by sergentum** [comment]
I have this in service-example.conf

```
    ssl_certificate         SSL_CERT;
    ssl_certificate_key     SSL_KEY;
    ssl_trusted_certificate SSL_CHAIN_CERT;

```
I thought these placeholders will be replaced later...
Looks like example conf wasn't formed from template to actual config at all.

Here should be relative path isn't it?
upd, ok i understood that it will be interpreted into docker container so it should be absolute
upd2: finally it works, thanks guys very much for your attention.

There is next issue in log, but site works by https:
 OCSP_basic_verify() failed (SSL: error:27069076:OCSP routines:OCSP_basic_verify:signer certificate not found) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, peer: myip, certificate: "/etc/nginx/ssl/le-crt.pem"
Here probably the solution:
https://community.letsencrypt.org/t/strange-ocsp-errors/5693
Guys recommend to use chain.pem for ssl_certificate parameter

**Comment by umputun** [comment]
those are placeholders, the final file in conf.d

**Comment by paskal** [comment]
@sergentum could you please checkout current master version and see if the problem replicates? If it does, please share docker log after start of the container, first ~20 lines would be enough.

**Comment by paskal** [comment]
@sergentum does the current version in master works for you?

**Comment by sergentum** [comment]
@paskal i'm sorry, I had no time to set it up again. I certainly will check from scratch and report here, but can't say when exactly.

**Comment by sergentum** [comment]
ok, finally i checked once again and looks like it works, but i have few unclear moments.
```
    ssl_certificate         SSL_CERT;
    ssl_certificate_key     SSL_KEY;
    ssl_trusted_certificate SSL_CHAIN_CERT;
```
Still the same, I thought that was the reason, but now I see that it works with theese placeholders fine.

2. Don't understand why default location of service-example -   `location /api/ {`
3. Also I don't understand why map files as volumes to nginx?
Why don't use whole folder mapping to docker and user will just add file for new site, without need to add mapping for each file?

**Comment by paskal** [comment]
Re replacement: `SSL_CERT` and others are replaced in a copy of the original file you provide to the container.

Re default location: it's just an example, you are not supposed to use it as-is, package assumes that you are already familiar with Nginx configuration.

Re files as volumes instead of a folder: good question, I can't think of any reason aside from historical reasons. @umputun?

**Comment by umputun** [comment]
I'm not sure how you plan to map the folder unless you are going to provide all files in /etc/nginx.

**Comment by paskal** [comment]
You could provide something like `/etc/nginx/sites-enabled.d/` instead of listing individual files, that's the idea.

Actually, I have a list of ~8 files in my biggest setup, and it sounds sane to have a directory mapping instead.

**Comment by sergentum** [comment]
i propose change that line
./etc/service-example.conf:/etc/nginx/service.conf
to
./etc/:/etc/nginx/

and that's it. If there is nothing interesting happening with config files like lines replacement or smth like that.

**Comment by paskal** [comment]
That's not good, Nginx provides other configuration files and files structure we're not interested in destroying.

**Comment by sergentum** [comment]
sorry, that's mistake. I meant the same you proposed earlier - map folder:
sites-enabled:/etc/nginx/sites-enabled.d/

**Comment by paskal** [comment]
@sergentum I'll think about how to implement it properly.

**Comment by paskal** [comment]
@sergentum it will be done in #49. I wonder if you have any other issues aside from that or this issue can be resolved?

**Comment by sergentum** [comment]
This one can be closed I guess, thanks.
