### ISSUE TITLE
ocsp.int-x3.letsencrypt.org could not be resolved

### ISSUE THREAD

**Issue by vtoupet** [nginx-le/nginx-le#44]
I am having an error message concerning certificate status checking:

[error] 35#35: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/ssl/le-crt.pem

For your information, I am using network_mode: host. Firewall is properly configured (both TCP and UDP 53 port opened).

Typing "nslookup ocsp.int-x3.letsencrypt.org" from within the container works fine.

Any thoughts?

**Comment by paskal** [comment]
Do you have [resolver](http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver) variable set somewhere and could you reach that host?

**Comment by vtoupet** [comment]
@paskal no I have not. Should I add one ? Within my service.conf file?

**Comment by paskal** [comment]
@vtoupet it's in the [default nginx.conf](https://github.com/nginx-le/nginx-le/blob/2aa5baf711ce8a0cd35b4fc856016d93be682989/conf/nginx.conf#L45) which is used if you don't override it. My point is you should check DNS requests from inside the container not without settings but specifically against 8.8.8.8 which is used for OCSP Stapling: `nslookup ocsp.int-x3.letsencrypt.org 8.8.8.8`

If it doesn't work, here is your problem. You can change it to something like [that](https://github.com/nginx-le/nginx-le/blob/78a363dfa9df7d03adffd46f92719781f43bb2c8/example/webrtc/etc/service.conf#L31) to make it work: `resolver 127.0.0.11 ipv6=off;`
If it does, I don't know but I suggest to try run the same in some other env to make sure the problem is with your environment and not the settings + nginx-le container combination, and if you have network restrictions then trying to lift them all to see if it's the cause.

**Comment by vtoupet** [comment]
I don't override the nginx.conf.

I've checked and nslookup work well:
```
docker exec -it nginx /bin/sh
/ # nslookup ocsp.int-x3.letsencrypt.org 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8 dns.google

Name:      ocsp.int-x3.letsencrypt.org
Address 1: 2a02:26f0:e8::6856:6f88 g2a02-26f0-00e8-0000-0000-0000-6856-6f88.deploy.static.akamaitechnologies.com
Address 2: 2a02:26f0:e8::6856:6fb0 g2a02-26f0-00e8-0000-0000-0000-6856-6fb0.deploy.static.akamaitechnologies.com
Address 3: 104.123.50.123 a104-123-50-123.deploy.static.akamaitechnologies.com
Address 4: 104.123.50.43 a104-123-50-43.deploy.static.akamaitechnologies.com
```
Removing all firewall rules (all ports accepted) does not help

**Comment by paskal** [comment]
I wonder if that can be related to IPv6, can you please check that?

**Comment by vtoupet** [comment]
I've just replace the resolver line with `resolver 8.8.8.8 ipv6=off;`. I let it run to see if it works.

How often is it supposed to check the status ? I am wondering whether only few calls fails and not all (how can I know if some are passing?). I am saying that by looking at the frequency which is not regular.

```
nginx                 | 2020/10/13 07:57:38 [error] 38#38: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/ssl/le-crt.pem"
nginx                 | 2020/10/13 08:10:10 [error] 38#38: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/ssl/le-crt.pem"
nginx                 | 2020/10/13 08:25:07 [error] 38#38: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/ssl/le-crt.pem"
nginx                 | 2020/10/13 08:46:29 [error] 38#38: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/ssl/le-crt.pem"
nginx                 | 2020/10/13 08:54:17 [error] 38#38: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/ssl/le-crt.pem"
nginx                 | 2020/10/13 10:25:51 [error] 38#38: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/ssl/le-crt.pem"
nginx                 | 2020/10/13 10:43:33 [error] 38#38: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/ssl/le-crt.pem"
nginx                 | 2020/10/13 10:49:23 [error] 38#38: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/ssl/le-crt.pem"
nginx                 | 2020/10/13 11:15:07 [error] 38#38: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/ssl/le-crt.pem"
nginx                 | 2020/10/13 12:01:47 [error] 38#38: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/ssl/le-crt.pem"
```

**Comment by vtoupet** [comment]
Unfortunately it does not work better :-(

**Comment by vtoupet** [comment]
Allowing TCP/UDP traffic on port 53 was not sufficient. It looks like port 5353 is used instead.

The problem was a firewall configuration issue, though I don't understand why standard DNS port 53 is not used here.
