### ISSUE TITLE
image cannot be gracefully stopped

### ISSUE THREAD

**Issue by vtoupet** [nginx-le/nginx-le#51]
Restarting/stopping the container is not performed gracefully.

I would expect to have an exit code 0 (like the official nginx docker image), but i am getting error code 137 which means SIGKILL was sent after the graceful period of 10 seconds.

container should handle SIGTERM signal in order for nginx to wait for all open connections to complete before exiting

**Comment by sergey-cheperis** [comment]
Docker attempts a graceful shutdown by sending SIGTERM to the main process of the container which is `entrypoint.sh`, and this signal does not propagate to the nginx process.

The simplest solution I have found is explained here:
https://stackoverflow.com/questions/57554703/why-use-nginx-with-daemon-off-in-background-with-docker

Just need to change the last line of `entrypoint.sh` from:
`nginx -g "daemon off;"`
to:
`exec nginx -g "daemon off;"`

However, please also consider that for nginx, SIGTERM causes it to exit without waiting for requests to complete. For this kind of termination, SIGQUIT should be used. This can be achieved by adding `STOPSIGNAL SIGQUIT` to the `Dockerfile`.

**Comment by paskal** [comment]
@sergey-cheperis feel free to prepare a PR with a proper fix if you want, I don't think it will be a problem to merge it.
