### ISSUE TITLE
Challenge failed for domain

### ISSUE THREAD

**Issue by almsafras** [nginx-le/nginx-le#52]
**Dear friends.

Please help Me on this Issue,**

root@Hiradio:~# sudo certbot renew --dry-run
Saving debug log to /var/log/letsencrypt/letsencrypt.log

Processing /etc/letsencrypt/renewal/radio.thehiradio.com.conf

Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator nginx, Installer nginx
Simulating renewal of an existing certificate for radio.thehiradio.com
Performing the following challenges:
http-01 challenge for radio.thehiradio.com
Waiting for verification...
Challenge failed for domain radio.thehiradio.com
http-01 challenge for radio.thehiradio.com
Cleaning up challenges
Attempting to renew cert (radio.thehiradio.com) from /etc/letsencrypt/renewal/radio.thehiradio.com.conf produced an unexpected error: Some challenges have failed.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
/etc/letsencrypt/live/radio.thehiradio.com/fullchain.pem (failure)

** DRY RUN: simulating 'certbot renew' close to cert expiry
** (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
/etc/letsencrypt/live/radio.thehiradio.com/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
** (The test certificates above have not been saved.)

1 renew failure(s), 0 parse failure(s)

IMPORTANT NOTES:

The following errors were reported by the server:

Domain: radio.thehiradio.com
Type: unauthorized
Detail: Invalid response from
http://radio.thehiradio.com/.well-known/acme-challenge/eh02oE4D2wsBfcT-NYXnr3j5BQ4bIvRQEkwYboftCFQ
[139.59.239.209]: "\r\n404 Not
Found\r\n\r\n

404 Not
Found
\r\n
nginx/1.18.0 (Ub"
To fix these errors, please make sure that your domain name was
entered correctly and the DNS A/AAAA record(s) for that domain
contain(s) the right IP address.

**Comment by paskal** [comment]
Must be my changes, I’ll check. Please switch to previous version in order to get it working in the meantime.

**Comment by paskal** [comment]
Could you please post the docker-compose so it would be easier for me to reproduce the error?

**Comment by paskal** [comment]
Actually, I see that you are running certbot and not nginx-le, how this request is related to nginx-le?

**Comment by paskal** [comment]
Hey @almsafras, I think what you are looking for is [that documentation](https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins). I could assume from the command output that you are running certbot standalone, and in order for it to work there should a DNS A entry pointing to the machine you're running that from and HTTP port (80) should not be occupied with any other web server like Nginx or apache at the time you're running the certbot command.

I hope that should be enough to help your troubleshooting and if it's not please update the issue and I'll try to help. I'll close it until further communication from you if you don't mind.
