### ISSUE TITLE
support multiple config files

### ISSUE THREAD

**Issue by umputun** [nginx-le/nginx-le#6]
`entrypoint.sh` runs sed on `/etc/nginx/conf.d/service.conf` only. However if multiple files mapped it should run on all of them.

**Comment by akoppela** [comment]
Is https://github.com/umputun/nginx-le/commit/ee2c19e0ad065fb02536df162223cc434c483e4d meant to be used for multiple config files? Or another question is why it's not in `master` yet?

**Comment by umputun** [comment]
> Is ee2c19e meant to be used for multiple config files?

yes

> why it's not in master yet?

Good question. Merged.
