### ISSUE TITLE
Update "LE_FQDN" without restart?

### ISSUE THREAD

**Issue by cheng6563** [nginx-le/nginx-le#60]
update .conf without restart is fine, because can use `nginx -s reload`.
but how it should be done update "LE_FQDN" env?

**Comment by paskal** [comment]
It's not possible with this project as far as I know, so if you want to have an Nginx running with let's encrypt certificate with the least downtime possible, you should switch to using Nginx + certbot container directly so that the certificate renewal would be decoupled from the Nginx.
