### ISSUE TITLE
Make preferred chain configurable

### ISSUE THREAD

**Issue by junousi** [nginx-le/nginx-le#64]
Been using `umputun/nginx-le:latest` for a few years, and recently getting some scanner complaints about

```
|-Subject   : O=Digital Signature Trust Co./CN=DST Root CA X3
|-Not After : Sep 30 14:01:15 2021 GMT
```

This hasn't resolved over a few renewals. I presume this is related to https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ somehow. IIUC for a long tail transition period there is still some kind of benefit in maintaining, or at least not disallowing, the "long chain" which ties to the X3 root. But in the long term the X1 / ISRG root would be preferrable.

I modified `le.sh` amending `--preferred-chain "ISRG Root X1"`, ran it, copied new key/cert/chain files in place, stop+started container. At least the complaint about 2021 expired CA went away, though this created some other issues; full chain was not included by default, R3 intermediary listed as "Extra download".

I am not entirely sure if shifting from the long chain to short chain / ISRG Root X1 would even entail some change in the way the key/cert/chain are copied, or if something that works for me could break things for others, hence not making a pull request.

But thought it might be worthile to open an Issue / feature request. Could there be something like a default variable with override capability

```
export LE_PREFERRED_CHAIN="ISRG Root X1"
...
certbot certonly ...  --preferred-chain "${LE_PREFERRED_CHAIN}" ...
```

?

Or if there's some way to do this already that I didn't think of, please advise and then let's close this Issue.

**Comment by paskal** [comment]
The better way is to add `LE_ADDITIONAL_OPTIONS`, which would allow anything, rather than specifying that option. Feel free to send the PR with the change.

**Comment by junousi** [comment]
Aye, just need to figure out is my `sh` really this rusty or something else going on when trying to feed anything whitespace delimited

```
/ # export LE_ADDITIONAL_OPTIONS='--version --version'
/ # echo certbot "${LE_ADDITIONAL_OPTIONS}"
certbot --version --version
/ # $(echo certbot "${LE_ADDITIONAL_OPTIONS}")
certbot 1.16.0
/ # certbot "${LE_ADDITIONAL_OPTIONS}" 2>&1 | tail -1
certbot: error: unrecognized arguments: --version --version
```

Presuming you'd want the last form for the PR and that specifically errors out regardless if it's the `--preferred-chain` or `--version` or anything else. `/usr/bin/certbot` only touches `sys.argv[0]` not the others so probably not related. Will test more with actual renewals when rate limit has ended.

**Comment by junousi** [comment]
@paskal now had a chance to look at this properly, and unfortunately I'm struggling to make this work with more complex arguments that may contain whitespace in addition to the delimiter whitespace. Tried various `set --` approaches, mangling `IFS` before processing the input variable with standard `sh` tooling, and so on. Still basically stuck at `certbot: error: unrecognized arguments: --preferred-chain 'ISRG Root X1'`.

Just to double check, should one presume that the additional options MUST come from a single *whitespace* delimited environment variable? Like in the commented out example [here](https://github.com/nginx-le/nginx-le/compare/master...junousi:nginx-le:addtl_opts?expand=1).

Pondering would it be more robust to pass these e.g. from a `\n` delimited string (or file). I'd like to avoid making a PR from anything based on `eval` if possible, but currently it seems like the easiest approach to let something like `eval` render the command before feeding it to python.

[Another](https://github.com/nginx-le/nginx-le/compare/master...junousi:nginx-le:addtl_opts_2?expand=1) approach could be to implement a dedicated extra options parser, which sorta-kinda-works for me, but probably not for all possible use cases. And even there one would need to further account for mismatched `'''` and typos and such in a more robust manner.

**Comment by paskal** [comment]
I think `certbot certonly -t -n --agree-tos --renew-by-default --email "${LE_EMAIL}" --webroot -w /usr/share/nginx/html -d ${LE_FQDN} ${LE_ADDITIONAL_OPTIONS}` should be enough. No need to check if that variable is present and non-zero.
